### ISSUE TITLE
Unable to run  demo.ipynb

### ISSUE THREAD

**Issue by savvyds** [auspicious3000/SpeechSplit#1]
To Run Demo
(done) Download pre-trained models to assets
(done) Download the same WaveNet vocoder model as in AutoVC to assets
(done) wavenet_vocoder git checkout 44e0e36 for more information, please refer to
(done) Run demo.ipynb

ModuleNotFoundError: No module named 'synthesis'

**Comment by auspicious3000** [comment]
Please run the vocoder part in the vocoder folder, and place the vocoder checkpoint in an accessible folder.

**Comment by savvyds** [comment]
Still no luck, I've created a copy on Colab, can you check what's  missing? 
https://colab.research.google.com/drive/106I-FARUyAbBVTH3BpxhyAflDaS0O0cQ?usp=sharing

**Comment by auspicious3000** [comment]
README updated. Or refer to AutoVC for more vocoder related information. I did not include much info here for vocoder because it is the same as in AutoVC.

**Comment by PigpigF** [comment]
> To Run Demo
> (done) Download pre-trained models to assets
> (done) Download the same WaveNet vocoder model as in AutoVC to assets
> (done) wavenet_vocoder git checkout 44e0e36 for more information, please refer to
> (done) Run demo.ipynb
> 
> ModuleNotFoundError: No module named 'synthesis'

I meet the same question，have you solved it？

**Comment by AndroYD84** [comment]
I'm facing the same issue, anyone solved it?

**Comment by niu0717** [comment]
@AndroYD84 
1.You just need copy the 'synthesis.py' from [AutoVC](https://github.com/auspicious3000/autovc).
2.pip install wavenet_vocoder.

**Comment by molo32** [comment]
How do I solve this error when executing the last cell?


```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-41-89e434475956> in <module>()
     10     os.makedirs('results')
     11 
---> 12 model = build_model().to(device)
     13 checkpoint = torch.load("/content/SpeechSplit/checkpoint_step001000000_ema.pth")
     14 model.load_state_dict(checkpoint["state_dict"])

/root/wavenet_vocoder/autovc/synthesis.py in build_model()

AttributeError: 'HParams' object has no attribute 'builder'
```

**Comment by sbkim052** [comment]
@molo32 
Have you fixed it?

**Comment by JVision** [comment]
I met the same problem.
