### ISSUE TITLE
There is exception when i run the main.py! How can i fix it?

### ISSUE THREAD

**Issue by niu0717** [auspicious3000/SpeechSplit#13]
![image](https://user-images.githubusercontent.com/45747807/95941421-50575400-0e13-11eb-9305-20fb75df99c6.png)
The dateset is your provided  training data . How can i fix it? 
Thx :) !

**Comment by niu0717** [comment]
https://github.com/auspicious3000/SpeechSplit/blob/1ae3c6c02ea606d5dd024f2395902f531b875227/data_loader.py#L107

The len(aa) is a scala, but  the type of len_crop is ndArray. The result of 'len(aa) - len_crop' is also ndArray. However, the second params of np.random.randint()  need a int value. Maybe there are some problems？

**Comment by auspicious3000** [comment]
please update numpy or use len_crop[0]
