### ISSUE TITLE
'pad_seq_to_2' from utils is not found

### ISSUE THREAD

**Issue by sachaker** [auspicious3000/SpeechSplit#2]
Hi there,

I am getting the following error:

**ImportError: cannot import name 'pad_seq_to_2'**

No documentation online seems to support this function in the package 'utils'. I would be really grateful to have some clarity on this issue!

Thanks :)

**Comment by auspicious3000** [comment]
There is a function called pad_seq_to_2 in utils. You should be able to import it from utils.

**Comment by sachaker** [comment]
Thanks for the quick response.

Just to be 100% sure:`pip install utils` ?

**Comment by sachaker** [comment]
pad_seq_to_2 isn't a function of the package I have installed

**Comment by auspicious3000** [comment]
No need to use pip, utils is not a package. 
utils is a file in this repo. You can find pad_seq_to_2 in utils simply using your browser.

**Comment by sachaker** [comment]
Such a silly oversight on my part—sorry about that. I tried to run the notebook in isolation on Google Colab with only /assets.
