### ISSUE TITLE
Help with the missing synthesis module in the demo

### ISSUE THREAD

**Issue by shubham-IISc** [auspicious3000/SpeechSplit#3]
Hi, 
Thanks for this amazing work!
I was quickly trying to run the demo. I am currently stuck with the **synthesis** module being imported to generate the audio from mels.
Kindly let me know where can I find it!

Thanks,
Shubham

**Comment by shubham-IISc** [comment]
found the answer in previous issues. closing it.

**Comment by t-hyun** [comment]
gg
