### ISSUE TITLE
What `demo.pkl` consists of ?

### ISSUE THREAD

**Issue by CYT823** [auspicious3000/SpeechSplit#35]
Is anyone know how to make a file like `demo.pkl`?
I've tried to print a data out, but I still have no idea. Below is my code and what I got: 

```
demoData = pickle.load(open(os.path.join('assets', 'demo.pkl'), "rb"))
    print(demoData[0][0])
    print(demoData[0][1].shape)       
    print(demoData[0][2][0].shape)
    print(demoData[0][2][1].shape)
    print(demoData[0][2][2])
    print(demoData[0][2][3])
```
``` 
result:
>> p226
>> (1, 82)
>> (135, 80)
>> (135,)
>> 135
>> 003002
```
I suppose it contains 3 things:
1. speaker name
2. speaker id
3. ??? → Could anyone give me a hint about these things? and how can I make one by myself? 

Thanks in advance

**Comment by auspicious3000** [comment]
Instead of looking at demo.pkl, please look at how the demo uses demo.pkl. Then you can easily figure out what you need to construct a demo.pkl. It does NOT need to be the same format as my demo.pkl as long as it contains all necessary inputs for the demo code.

**Comment by CYT823** [comment]
Thanks @auspicious3000. I'll go check this out.

**Comment by oliver8459** [comment]
> Thanks @auspicious3000. I'll go check this out.

hi, i have the same issue with you, did you figure this out?
