### ISSUE TITLE
No module named 'synthesis'

### ISSUE THREAD

**Issue by ThorChadMerlin** [auspicious3000/SpeechSplit#37]
I want to run the demo having been interested by the paper, but I am facing problems as follows:

## To reproduce

* Clone the repo
* Install dependencies
* ```pip install wavenet-vocoder==0.1.1```
* Add trained models to assets
* Run 'demo.ipynb' cell 1, then cell 2
## Issue 
The following error is thrown:
``` 
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-e12167bbae28> in <module>
      4 import pickle
      5 import os
----> 6 from synthesis import build_model
      7 from synthesis import wavegen
      8 

ModuleNotFoundError: No module named 'synthesis' 
```

I feel this is because the install of wavenet-vocoder through pip does not install the necessary module 'synthesis'. Instructions are not completely clear on the wavenet-vocoder repo, or here how this synthesis module is accessed.

Any help would be appreciated!

**Comment by auspicious3000** [comment]
Please refer to AutoVC if you have any problems with the vocoder part, because they share the same vocoder scripts.

**Comment by ThorChadMerlin** [comment]
I have been over the AutoVC repo repeatedly, and how it relates to this repo is not entirely obvious in terms of the vocoder scripts. 

 I'm slightly lost as to how the synthesis module is meant to be accessed from the SpeechSplit repo. Are additional files meant to be copied over from AutoVC into SpeechSplit? What does your repo look like if it can run this code with no issues?
 Thanks any help!

**Comment by auspicious3000** [comment]
Yes, for example you need to copy synthesis from AutoVC. The rest should be straightforward once you understand the code.
Many beginners ask similar questions, you can find detailed answers in other issues. There is also someone made working pull on this.
