### ISSUE TITLE
How the utterance id in demo.pkl is calculated?

### ISSUE THREAD

**Issue by inconnu11** [auspicious3000/SpeechSplit#4]
In the file demo.pkl, the last dimension is utterance id and it is designated as 003002 in demo. How to find the corresponding wav in VCTK corpus whose id is 003002 in your demo? And I am wondering how the utterance id is obtained. It seems that you doesn't mention how to get the utterance id according to the VCTK corpus.
Thank you!

**Comment by auspicious3000** [comment]
The utterance id can be anything as long as you know what that utterance is. You can name it 123456 or 12138, etc. 
003002 is just one utterance cut from the vctk corpus, which I personally name it 003002

**Comment by inconnu11** [comment]
Got it. Thanks!

**Comment by c1a1o1** [comment]
Can you make the right demo.pkl file?
