### ISSUE TITLE
Question: how many speakers was trained in pre-trained model?

### ISSUE THREAD

**Issue by Kurei-Fujiwara** [auspicious3000/SpeechSplit#42]
Hi, thanks for the great work.
Sorry for the rudimentary question.
I have a question about the pre-trained model in demo.ipybn.
In the paper, it says that it was trained by 20 speakers, but the speaker ID vector used in demo.ipynb has a size of 82, and it looks like it has information for 82 speakers.
Please tell me how many speakers were used in the pre-trained model and why the speaker ID in demo.ipynb has a size of 82.

**Comment by auspicious3000** [comment]
The speaker emb has 82 dims because there are 82 speakers in the dataset. Only 20 of them were used.
