### ISSUE TITLE
Learning rate for P (F0_Converter)

### ISSUE THREAD

**Issue by ThorChadMerlin** [auspicious3000/SpeechSplit#47]
I have integrated training for P in solver.py but am unsure of what learning rate to use. 

The default for G is 0.001, but I doubt this is also correct for P.

What initial LR should I use for P?

Many thanks.

**Comment by auspicious3000** [comment]
The default for G should be 0.0001 instead of 0.001. 
The same works for P as well, but feel free to try other lrs.

**Comment by ThorChadMerlin** [comment]
My mistake - 0.0001 is correct. Many thanks for your fast response.
