### ISSUE TITLE
Training bottleneck hparams

### ISSUE THREAD

**Issue by ThorChadMerlin** [auspicious3000/SpeechSplit#49]
Can I get a confirmation on tuning the bottlenecks inline with Appendix B.4?

* "The first operation is to increase the channel dimension of the encoder output" 
Does this refer to ```dim_enc```, ```dim_enc_2``` and ```dim_enc_3```? 

* "The second operation is to increase the sampling rate of the down-sampled code"
Does this refer to ```freq```, ```freq_2``` and ```freq_3```?

**Comment by auspicious3000** [comment]
Yes
