### ISSUE TITLE
How can we construct a demo.pkl-like file? 

### ISSUE THREAD

**Issue by janeyeon** [auspicious3000/SpeechSplit#6]
demo.pkl is a list of 6 entries.

1. What does each entry of the list represent? I figured out the last entry is for identification. But I still have no idea what the other entries mean.

2. How can we manually construct a demo.pkl-like file? Are there any APIs to make one?

Thank you.

**Comment by auspicious3000** [comment]
One can easily figure that out by looking at demo.ipynb

**Comment by woo1** [comment]
> One can easily figure that out by looking at demo.ipynb

Thanks for sharing your code.
I watched demo.ipynb and your paper.
I can figure out the role of the values.
But it is hard to find how to implement that.
You might use pysptk library to get "x_trg" data. and the hopsize is 16 according to the paper.
(https://pysptk.readthedocs.io/en/latest/generated/pysptk.sptk.rapt.html)
But when I tried to make the data, it looks so different with demo.pkl data. 
I want to test with my own voice file.

Could you give us more detail information to make demo.pkl-like file?

**Comment by c1a1o1** [comment]
Can you make the right demo.pkl file?

**Comment by leijue222** [comment]
> One can easily figure that out by looking at demo.ipynb

demo.ipynb only load  a .pkl file, not construct a .pkl  file

**Comment by skol101** [comment]
@leijue222 you're talking about spk2gen.pkl .

Demo.pkl contains source voice (p226) and target voice (p231). The rest of data is a matrix. I am assuming it represent voice features of a particular speaker. 

From the demo.ipynb
x_org, f0_org, len_org, uid_org = sbmt_i[2]  
print(x_org)
[[0.43534297 0.34510893 0.28891113 ... 0.21939816 0.1917529  0.182401  ]
 [0.3884567  0.33501938 0.32049102 ... 0.28679007 0.23618948 0.22491907]
 [0.36167625 0.28442776 0.30069032 ... 0.3951543  0.35437956 0.29158577]
 ...
 [0.32710207 0.30764872 0.2712859  ... 0.30854747 0.27503774 0.23082325]
 [0.32770813 0.3195486  0.26296    ... 0.19346626 0.15659298 0.13683894]
 [0.2930235  0.28976902 0.2671687  ... 0.05634676 0.03487811 0.01842958]]
