### ISSUE TITLE
Training for encoder (i.e. embedding) usage only?

### ISSUE THREAD

**Issue by tobwei** [auspicious3000/SpeechSplit#60]
Sorry I just found your e-mail address and will thus just write you an e-mail about this - this can be deleted - sorry again for the inconveniences.

**Comment by jinny1208** [comment]
hi, just wondering what your question was since I am also interested in just using the encoder part only and not the decoder. 
And, if you don't mind, can you also post the reply to your question?
Thanks in advance.
