### ISSUE TITLE
Question about padding

### ISSUE THREAD

**Issue by summersunshine1** [auspicious3000/SpeechSplit#67]
I have a question about padding. It seems that the training of the model misses mask operation for padding.

**Comment by auspicious3000** [comment]
Could you provide the line numbers?

**Comment by summersunshine1** [comment]
In the model.py, it may be necessary for LSTM to do a mask for tokens with paddings.  In the solve.py, it may be required for masking the loss of padded tokens.

**Comment by auspicious3000** [comment]
Thanks for your suggestion. Please feel free to try it yourself and see how it works.
