### ISSUE TITLE
Is it very slow for the Wavenet vocoder to synthesize a voice

### ISSUE THREAD

**Issue by hhhuazi** [auspicious3000/SpeechSplit#69]
Hello, I use demo.ippynb synthesizes voice from mel, it takes 5 minutes to synthesize a voice. Isn't this too slow? Can I use HifiGAN's pre training model directly？Thank you for your answer！

**Comment by auspicious3000** [comment]
yes, that's the purpose

**Comment by hhhuazi** [comment]
Thank you for your answer! I found the pre training model of hifiGAN in github and added it, but the synthesized voice has no content, such as noise. Why? Do I need to use the VCTK dataset to train the HiFiGAN vocoder again? Does the dataset need to be divided?

**Comment by auspicious3000** [comment]
Yes. But you can also use the hifigan model under autovc or autopst.

**Comment by hhhuazi** [comment]
Are there any precautions for retraining vocoder?

**Comment by auspicious3000** [comment]
It should be straightforward.
