### ISSUE TITLE
Cuda error

### ISSUE THREAD

**Issue by popkingcorn** [auspicious3000/SpeechSplit#73]
I have an error:
Could not load symbol cublasGetSmCountTarget from cublas64_11.dll. Error code 127
Cuda version 11.3
Torch version 1.12.1+cu113

demo.ipynb still running with this error using cuda:0, but with speed ~ 80 it/s (3070ti).
I set to use cpu (i5-8400) and have speed ~95 it/s.
Is that normal and how to fix this error? 
How to reduce steps count to generate faster?
![console](https://user-images.githubusercontent.com/58981708/227786241-4914b553-facb-4b57-a929-544c73f60100.png)

**Comment by auspicious3000** [comment]
As you mentioned, this is a cuda error. It is best to post this question to pytorch or nvidia forum.
