### ISSUE TITLE
Spectrogram db scaling

### ISSUE THREAD

**Issue by ghostcaesar** [auspicious3000/SpeechSplit#8]
Hi, I am trying to change the wavenet vocoder to the melgan, however, I noticed the scaling of dB is different from what is generated in demo.ipynb, compared to what melgan generated.

![119137241_353270955716740_1578151265465205932_n](https://user-images.githubusercontent.com/10070633/93028289-0853de80-f667-11ea-9715-a0be8220ba19.png)

On the left is c.T from demo.ipynb plotted, while on the right is melgan generated spectrogram from wav files. Note the scale is different, one is positive, while the other is negative.

demo.ipynb spectrogram generates fine using wavenet, but generates garbage when fed into melgan. Scaling db values linearly to approximate melgan works ok when fed to melgan, but is there a proper method to convert between the db scalings?

**Comment by auspicious3000** [comment]
You can look at their respective ways of computing spectrograms.

**Comment by Nintorac** [comment]
@ghostcaesar do you mind sharing a snippet of how you're rescaling the mel's?

**Comment by ghostcaesar** [comment]
After looking through the SpeechSplit code, this is the proper scaling method

`mel = ((np.clip(c, 0, 1) * 100) -100 +16) /20`

**Comment by Nintorac** [comment]
Hmm maybe I am missing something.. I altered the vocoding section to look like the following but it still results in very phasey audio with some weird modulations that sounds kind of syllabic but nothing coherent.

Am I missing something

```
import torch
import librosa
import pickle
import os


vocoder = torch.hub.load('seungwonpark/melgan', 'melgan')
vocoder.eval()


for spect in spect_vc:
    name, c = spect
    c = torch.from_numpy(c).transpose(-1, -2)[None]
    print(name)
    mel = ((np.clip(c, 0, 1) * 100) -100 +16) /20
    with torch.no_grad():
        waveform = vocoder(mel).squeeze()
    sf.write('results/'+name+'.wav', waveform, 22050)
```

**Comment by ghostcaesar** [comment]
I was using this implementation

https://github.com/descriptinc/melgan-neurips

I also had to retrain the melgan model because melgan was sampling at 22050, while speechsplit uses 16000hz, and this causes the output wav to have a lower frequency for reasons I dont know. Retraininig melgan using 16000hz solves this problem.

The other difference is the clipping and rescaling was done before the transpose, although I dont think that will make any difference.

**Comment by Nintorac** [comment]
Makes sense, I guess I was overly optimistic to think it would just work. Would you mind sharing your re-trained melgan weights?

**Comment by ghostcaesar** [comment]
My model and training data is for specific application and not generalised. So it will not be useful for you. Probably best to train your own model making sure sampling rate is at 16000hz.

**Comment by inconnu11** [comment]
> Hi, I am trying to change the wavenet vocoder to the melgan, however, I noticed the scaling of dB is different from what is generated in demo.ipynb, compared to what melgan generated.
> 
> ![119137241_353270955716740_1578151265465205932_n](https://user-images.githubusercontent.com/10070633/93028289-0853de80-f667-11ea-9715-a0be8220ba19.png)
> 
> On the left is c.T from demo.ipynb plotted, while on the right is melgan generated spectrogram from wav files. Note the scale is different, one is positive, while the other is negative.
> 
> demo.ipynb spectrogram generates fine using wavenet, but generates garbage when fed into melgan. Scaling db values linearly to approximate melgan works ok when fed to melgan, but is there a proper method to convert between the db scalings?

Hi, there is one step "Extract spectrogram and f0: python make_spect_f0.py". Have you ever checked the range of mel spectrogram generated? What's the range of the mel spectrogram load from the npy file?
