### ISSUE TITLE
F0 mean and std

### ISSUE THREAD

**Issue by Nintorac** [auspicious3000/SpeechSplit#9]
Hey.

Do you know the mean and std calculated [here](https://github.com/auspicious3000/SpeechSplit/blob/master/make_spect_f0.py#L66) for the pre-trained weights??

Thanks

**Comment by auspicious3000** [comment]
The F0 mean and std are calculated using the F0, which has nothing to bo with pre-trained weights.

**Comment by Nintorac** [comment]
Oh, I see now. I thought the values were calculated over the entire dataset, my bad
